---
title: "Part2"
author: "Danshu"
date: "2023-03-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-data}
df1 <- read.csv("houseprices.csv")
df2 <- read.csv("houseprices2.csv")
```

Load packages:
  
```{r packs, message = FALSE}
# load packages
library(ggplot2)
library(tidyverse)
library(gridExtra)
library(dplyr)
library(countrycode)
library(arm)
library(visdat)
library(patchwork)
library(hrbrthemes)
library(viridis)
library(Metrics)
library(caret)
library(interactions)
library(DescTools)
library(naivebayes)
library(psych)
library(caret)
theme_set(theme_classic())
```

```{r setting}
options(scipen = 999)
```

Data pre-processing:

```{r pre-processing}
# view missings
vis_miss(df1)
```


```{r polt-price}
# visualization of distribution of house sale prices
hist(df1$SalePrice, main = "SalePrice", xlab = "price")
boxplot(df1$SalePrice, main = "SalePrice",xlab = "price", border = "brown",horizontal = TRUE)
```

```{r 1}
# check detail for each variable in data set
str(df1)
```

```{r 2}
d1<- df1%>%
  mutate(TotalBath = FullBath + HalfBath)
d1["GarageType"][is.na(d1["GarageType"])] <- "No Garage"
```


```{r 3}
# choose variables which need to be factorized
varschr <- c("Street", "LotShape", "LandContour", "Utilities", "Neighborhood", "BldgType", "HouseStyle","RoofStyle", "Foundation", "Heating", "CentralAir","Electrical","KitchenQual","GarageType")

# factor variables
d1[,varschr] <- lapply(d1[,varschr] , factor)

#check detail for each variable in data set after factorization
str(d1)
```
```{r 4}
# look varaibles
sapply(lapply(d1, unique), length)
```


```{r 6}
# drop variables which are not useful for the following logistic regression models
d2 <- subset(d1, select = -c(Id,FullBath,HalfBath))
lapply(d2[varschr], table)
```


```{r 7}
d2 <- subset(d2, select = -c(Utilities))
d2 <- na.omit(d2)
```


```{r}
match(c("Mix"),d2$Electrical)
match(c("Floor"),d2$Heating)
N <- c(1:398,400:1321,1323:dim(d2)[1])
```

```{r}
sapply(lapply(d2, unique), length)
```

```{r 6}
preds1 <- numeric(dim(d2)[1]-2)
absolute_error <- numeric(dim(d2)[1]-2)
for (i in N){
  fit1 <- lm(SalePrice~.,data=d2[-i,])
  preds1[i] <- predict(fit1,d2[i,])
  absolute_error[i] <- abs(preds1[i]-d2$SalePrice[i])
  }
summary(fit1)
```

```{r}
Mean_error <- sum(absolute_error)/length(N)
```


```{r selection}
#part 2
##three variables
intercept_only <- lm(d2$SalePrice ~ 1, data=d2)
full <- lm(d2$SalePrice ~ ., data=d2)
forward <- stepAIC(intercept_only,  scope=formula(full), steps = 3, direction='forward', trace=F)
forward$anova
```

```{r 7}
d3 <- subset(d2, select = c(SalePrice,OverallQual,GrLivArea,Neighborhood))
```

```{r 8}
preds2 <- numeric(dim(d3)[1])
absolute_error2 <- numeric(dim(d3)[1])
for (i in 1:dim(d3)[1]){
  fit2 <- lm(SalePrice~.,data=d3[-i,])
  preds2[i] <- predict(fit2,d3[i,])
  absolute_error2[i] <- abs(preds2[i]-d3$SalePrice[i])
  }
summary(fit2)
Mean_error2 <- sum(absolute_error2)/dim(d3)[1]
```

```{r 9}
##more variables
forward2 <- stepAIC(intercept_only, scope=formula(full), direction='forward', trace=F) #best model
```

```{r 10}
d4 <- forward2$model
names(d4)[names(d4) == "d2$SalePrice"] <- "SalePrice"
```

```{r 11}
preds3 <- numeric(dim(d4)[1])
absolute_error3 <- numeric(dim(d4)[1])
for (i in 1:dim(d4)[1]){
  fit3 <- lm(SalePrice~.,data=d4[-i,])
  preds3[i] <- predict(fit3,d4[i,])
  absolute_error3[i] <- abs(preds3[i]-d4$SalePrice[i])
  }
summary(fit3)
Mean_error3 <- sum(absolute_error3)/dim(d4)[1]
```


```{r 12}
#part3
plot(fit1)
```

```{r 13}
# check the normality of SalePrice
qqnorm(d2$SalePrice, ylab = "SalePrice")
qqline(d2$SalePrice)
hist(d2$SalePrice, main = "SalePrice", xlab = "price")
```

```{r 14}
# add log
d5 <- d2%>%
  mutate(LogSalePrice = log(SalePrice))
qqnorm(d5$LogSalePrice, ylab = "Log(SalePrice)")
qqline(d5$LogSalePrice)
hist(d5$LogSalePrice, main = "Log(SalePrice)", xlab = "price")
```

```{r 15}
d5 <- subset(d5, select = -c(SalePrice))
```

```{r 16}
preds4 <- numeric(dim(d5)[1]-2)
absolute_error4 <- numeric(dim(d5)[1]-2)
for (i in N){
  fit4 <- lm(LogSalePrice~.,data=d5[-i,])
  preds4[i] <- predict(fit4,d5[i,])
  absolute_error4[i] <- abs(exp(preds4[i])-exp(d5$LogSalePrice[i]))
  }
summary(fit4)
Mean_error4 <- sum(absolute_error4)/length(N)
```

```{r 17}
# interaction
fit5 <-lm(LogSalePrice~(LotArea + Street + LotShape + LandContour + Neighborhood + BldgType + HouseStyle + OverallQual + OverallCond + YearBuilt + RoofStyle + Foundation + TotalBsmtSF + Heating + CentralAir + Electrical + GrLivArea + BedroomAbvGr + KitchenAbvGr + KitchenQual + TotRmsAbvGrd + Fireplaces + GarageType + GarageArea + MoSold + YrSold + TotalBath)*OverallQual, data = d5)
fit6 <- step(fit5, trace=F)
summary(fit6)
```

```{r interaction-plot}
# interaction between OverallQual and LandContour
interact_plot(fit5, pred = OverallQual, modx = LandContour) + labs(y ="Log(SalePrice)", x = "Overall material and finish quality")
```



```{r 18}
fit7 <-lm(LogSalePrice~LotArea + Street + LotShape + LandContour + Neighborhood + BldgType + HouseStyle + OverallQual + OverallCond + YearBuilt + RoofStyle + Foundation + TotalBsmtSF + Heating + CentralAir + Electrical + GrLivArea + BedroomAbvGr + KitchenAbvGr + KitchenQual + TotRmsAbvGrd + Fireplaces + GarageType + GarageArea + MoSold + YrSold + TotalBath + LandContour:OverallQual, data = d5)
summary(fit7)
formula <- formula(fit7)
```

```{r 19}
preds5 <- numeric(dim(d5)[1]-2)
absolute_error5 <- numeric(dim(d5)[1]-2)
for (i in N){
  fit8 <- lm(formula,data=d5[-i,])
  preds5[i] <- predict(fit8,d5[i,])
  absolute_error5[i] <- abs(exp(preds5[i])-exp(d5$LogSalePrice[i]))
  }
summary(fit8)
Mean_error5 <- sum(absolute_error5)/length(N)
```


